extends SceneTree
const Registry := preload("res://scripts/network/room_registry.gd")
const Codec := preload("res://scripts/network/protocol_codec.gd")
const Projector := preload("res://scripts/network/snapshot_projector.gd")

func _initialize() -> void:
	var registry = Registry.new()
	var host = registry.create(1, "房主")
	assert(host.ok and int(host.seat) >= 0 and int(host.seat) < 4)
	var guest := registry.join(2, "玩家二")
	assert(guest.ok and int(guest.seat) != int(host.seat))
	assert(not registry.join(2, "重复").ok)
	assert(registry.set_ready(2, true))
	assert(not registry.can_start())
	assert(registry.set_ready(1, true))
	assert(registry.can_start())
	registry.reset_guest_ready()
	assert(not registry.can_start())
	assert(registry.public_members().size() == 2)
	var codec = Codec.new()
	var encoded := codec.encode({"protocol_version": 1, "kind": "ready", "ready": true})
	assert(not encoded.is_empty() and codec.decode(encoded).ok)
	assert(not codec.decode('{"protocol_version":2,"kind":"ready"}'.to_utf8_buffer()).ok)
	assert(not codec.encode({"protocol_version": 1, "kind": "settlement", "description": "番".repeat(512)}).is_empty())
	assert(codec.encode({"protocol_version": 1, "kind": "settlement", "description": "番".repeat(4097)}).is_empty())
	assert(codec.encode({"protocol_version": 1, "kind": "bad", "object": Node.new()}).is_empty())
	var players := []
	for seat in range(4): players.append({"seat": seat, "nickname": "P%d" % seat, "hand_tiles": [{"id": seat * 10 + 1}], "hand_count": 1, "melds": []})
	var view := Projector.new().project({"current_turn_seat": 2, "current_dealer_seat": 1, "players": players, "round_winners": [], "human_can_discard": true, "human_reaction_options": {}}, 2)
	assert(view.current_turn_seat == 0 and view.current_dealer_seat == 3)
	assert(view.players[0].hand_tiles.size() == 1)
	for seat in range(1, 4): assert(not view.players[seat].has("hand_tiles"))
	var settlement_view := Projector.new().project({"current_phase": 7, "players": players}, 2)
	for seat in range(4): assert(settlement_view.players[seat].hand_tiles.size() == 1)
	assert(not view.has("ai_core_debug") and not view.has("pending_ai_turn_decision"))
	print("ROOM_PROTOCOL_PRIVACY_PASS")
	quit(0)
